blog/urls.py
from django.urls import path,include

from .views import (
    PostUpdateView,
    PostDeleteView,
    TagPostListView,
    UserPostListView,
    post_create,
)
from . import views

urlpatterns = [
    path('', views.home, name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('<post_id>/detail_view/', views.post_detail, name='post-detail'),
    path('post/new/', views.post_create, name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('tag/<str:tagname>',TagPostListView.as_view(),name='tag_posts'),
]

calendarapp/urls.py
from django.urls import path

from . import views

app_name = 'calendarapp'
urlpatterns = [
    path('', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.create_event, name='event_new'),
    path('event/edit/<int:pk>/', views.EventEdit.as_view(), name='event_edit'),
    path('event/<int:event_id>/details/', views.event_details, name='event-detail'),
    path('add_eventmember/<int:event_id>', views.add_eventmember, name='add_eventmember'),
    path('event/<int:pk>/remove', views.EventMemberDeleteView.as_view(), name="remove_event"),
    path('add_student_to_event/',views.add_student_to_event, name='add_student_to_event'),
    path('export/ps_csv/<event_id>', views.export_presentees_csv, name='export_presentees_csv'),
    path('export/abs_csv/<event_id>', views.export_absentees_csv, name='export_absentees_csv'),
    path('news/add', views.add_latest_news, name='add_news'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('k/', include('filer.server.urls')),
    path('', include('user.urls')),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('nadmin/',admin.site.urls),
    path('comment/', include('comment.urls')),
    path("a/", include("account.urls")),
    path('tinymce/', include('tinymce.urls')),
    path("b/", include("blog.urls")),
    path("t/", include("teams.urls")),
    path("m/", include("meeting.urls")),
    path("a_r/", include("attendance_request.urls")),
    path("c/", include("contacts.urls")),
    path("e/", include("calendarapp.urls")),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('td/', include('todo.urls', namespace="todo")),
    path('filer/', include('filer.urls')),
    # path('robots.txt',robots),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

calendarapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Event(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    next_level = models.CharField(max_length=50)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    created_date = models.DateTimeField(auto_now_add=True)
    cgpa = models.DecimalField(max_digits=4,decimal_places=2,default=0.0)
    tenth = models.DecimalField(max_digits=4,decimal_places=2,default=0.0)
    inter = models.DecimalField(max_digits=4,decimal_places=2,default=0.0)
    is_completed = models.BooleanField(default=False)
    disable_add = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('calendarapp:event-detail', args=(self.id,))

    @property
    def get_html_url(self):
        url = reverse('calendarapp:event-detail', args=(self.id,))
        return f'<a href="{url}" data-toggle="tooltip" data-placement="top" title="{self.title} Level: {self.next_level}" style="text-decoration:none;color:white;font-size:1.75vh;"> {self.title} </a>'


class EventMembers(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    students = models.ManyToManyField(User)


class AddManualMembers(models.Model):
    get_class = models.IntegerField()
    get_rolls = models.TextField()

class AddLatestNews(models.Model):
    created_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField()
    post_data = models.TextField()

    def get_absolute_url(self):
        return reverse('home')

calendarapp/forms.py
from django.forms import ModelForm, DateInput
from calendarapp.models import Event, EventMembers
from django import forms
from .models import *

class EventForm(ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    exclude = ['user']

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats to parse HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)



class AddMemberForm(forms.ModelForm):
  class Meta:
    model = AddManualMembers
    fields = '__all__'

class AddLatestNewsForm(forms.ModelForm):
    class Meta:
        model = AddLatestNews
        widgets = {
            'end_time':DateInput(attrs={'type':'datetime-local'},format='%Y-%m-%dT%H:%M'),
        }
        exclude=['user']
    def __init__(self,*args,**kwargs):
        super(AddLatestNewsForm,self).__init__(*args,**kwargs)
        self.fields['end_time'].input_format = ('%Y-%m-%dT%H:%M',)

calendarapp/views.py
# cal/views.py

from datetime import datetime, date
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.utils.safestring import mark_safe
from datetime import timedelta
import calendar
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .filters import *
from .models import *
from .utils import Calendar
from .forms import EventForm, AddMemberForm,AddLatestNewsForm
import csv
from django.contrib.auth.models import User
from django.db.models import F
from decimal import Decimal
from django.contrib.auth.models import User

def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

class CalendarView(LoginRequiredMixin, generic.ListView):
    login_url = 'account_login'
    model = Event
    template_name = 'calendarapp/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

@login_required(login_url='account_signup')
def create_event(request):
    form = EventForm(request.POST or None)
    if request.POST and form.is_valid():
        title = form.cleaned_data['title']
        description = form.cleaned_data['description']
        start_time = form.cleaned_data['start_time']
        end_time = form.cleaned_data['end_time']
        next_level = form.cleaned_data['next_level']
        cgpa = form.cleaned_data['cgpa']
        tenth = form.cleaned_data['tenth']
        inter = form.cleaned_data['inter']
        Event.objects.get_or_create(
            user=request.user,
            title=title,
            description=description,
            start_time=start_time,
            end_time=end_time,
            next_level=next_level,
            cgpa=cgpa,
            tenth=tenth,
            inter=inter,
        )
        event=Event.objects.get(title=title)
        EventMembers.objects.create(event=event)
        return HttpResponseRedirect(reverse('calendarapp:calendar'))
    return render(request, 'calendarapp/event.html', {'form': form})

class EventEdit(generic.UpdateView):
    model = Event
    fields = ['title', 'description', 'start_time', 'end_time', 'next_level','tenth','inter','cgpa','disable_add','is_completed']
    template_name = 'calendarapp/event.html'

@login_required(login_url='/account/login/')
def event_details(request, event_id):
    event = Event.objects.get(id=event_id)
    print(event)
    eventmembers = EventMembers.objects.get(event=event)
    # Seggregating only current user section students
    eventmembers = eventmembers.students.filter(profile__section=request.user.profile.section,)#profile__cgpa__gte=event.cgpa,profile__tenth__gte=Decimal.from_float(event.tenth/9.5),profile__inter__gte=Decimal.from_float(event.inter/0.1)
    users = ClassFilter(request.GET, queryset=Profile.objects.filter(section=request.user.profile.section)) #cgpa__gte = event.cgpa,tenth__gte = Decimal.from_float(event.tenth/9.5),inter__gte = Decimal.from_float(event.inter/0.1)
    context = {
        'event':event,
        'eventmembers': eventmembers,
        'users':users,
    }
    return render(request, 'calendarapp/event-details.html', context)


def add_eventmember(request, event_id):
    forms = AddMemberForm()
    if request.method == 'POST':
        forms = AddMemberForm(request.POST)
        if forms.is_valid():
            member = EventMember.objects.filter(event=event_id)
            event = Event.objects.get(id=event_id)
            curr_class = forms.cleaned_data['get_classes']
            get_rollnos = forms.cleaned_data['get_rolls']
            get_rollnos = get_rollnos.split(',')
            curr_year = str(datetime.today().year-3)[2:]
            for i in get_rollnos:
                if len(i) == 1:
                    rollno = '12'+curr_year+'103'+curr_class+'00'+i
                else:
                    rollno = '12'+curr_year+'103'+curr_class+'0'+i
                get_user = User.objects.filter(rollno=rollno)
                event.students.add(user=get_user)

    context = {
        'form': forms
    }
    return render(request, 'calendarapp/add_member.html', context)


class EventMemberDeleteView(generic.DeleteView):
    model = EventMembers
    template_name = 'calendarapp/event_delete.html'
    success_url = reverse_lazy('calendarapp:calendar')


def add_student_to_event(request):
    user = get_object_or_404(User, id=request.POST.get('user_id'))
    event = get_object_or_404(Event, id=request.POST.get('event_id'))
    user.profile.num_drives_attempt=user.profile.num_drives_attempt+1
    event_members=EventMembers.objects.get(event=event)

    if event_members.students.filter(id=user.id).exists():
        user.profile.current_events.remove(event)
        event_members.students.remove(user)
        user.profile.save()
        data='r'
        return HttpResponse(data)
    else:
        user.profile.current_events.add(event)
        event_members.students.add(user)
        user.profile.save()
        data='a'
        return HttpResponse(data)



def export_presentees_csv(request, event_id):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="attendance_presentees.csv"'

    writer = csv.writer(response)
    event = Event.objects.get(id=event_id)
    writer.writerow(['EVENT TITLE', 'EVENT DESCRIPTION', 'EVENT START TIME'])
    writer.writerow([event.title, event.description, str(event.start_time)])
    writer.writerow(['Roll_No', 'NAME', 'CGPA'])
    users = EventMembers.objects.get(event=event).students.filter(profile__section=request.user.profile.section,).values_list('profile__roll_no', 'first_name', 'profile__cgpa')
    for user in users:
        writer.writerow(user)
    return response

def export_absentees_csv(request, event_id):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="attendance_absentees.csv"'

    writer = csv.writer(response)
    event = Event.objects.get(id=event_id)
    writer.writerow(['EVENT TITLE', 'EVENT DESCRIPTION', 'EVENT START TIME'])
    writer.writerow([event.title, event.description, str(event.start_time)])
    writer.writerow(['Roll_No'])
    users=User.objects.filter(profile__section=request.user.profile.section)
    users_set=list([str(user.profile.roll_no) for user in users])
    presentees = EventMembers.objects.get(event=event).students.filter(profile__section=request.user.profile.section,)
    presentees_set = list([str(user.profile.roll_no) for user in presentees])
    absentees=[user for user in users_set if user not in presentees_set]
    for user in absentees:
        writer.writerow([user])
    return response

@login_required(login_url='/account/login/')
def add_latest_news(request):
    form = AddLatestNewsForm(request.POST)
    if request.method == 'POST':
        form = AddLatestNewsForm(request.POST)
        if form.is_valid():
            end_time = form.cleaned_data['end_time']
            post_data = form.cleaned_data['post_data']
            AddLatestNews.objects.get_or_create(
                end_time=end_time,
                post_data = post_data,)
        return HttpResponseRedirect(reverse('calendarapp:calendar'))
    context = {
        'form': form
    }
    return render(request, 'calendarapp/add_news.html', context)

calendarapp/templates/calendarapp/add_member.html
{% extends 'user/base.html' %}

{% block title %}
Add EventMember
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'calendarapp:calendar' %}"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

calendarapp/templates/calendarapp/add_news.html
{% extends 'user/base.html' %}

{% block title %}
Add EventMember
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'calendarapp:calendar' %}"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

calendarapp/templates/calendarapp/base.html
<!-- cal/templates/cal/base.html -->

{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <title>Django Calendar App</title>
</head>
<body>

  {% block content %}

  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

calendarapp/templates/calendarapp/calendar.html
{% extends 'user/base.html' %}

{% block content %}
<div>
    <!--<div class='container d-flex justify-content-center'>-->
    <a class="btn btn-light m-2 p-2" style="color: white; border-radius:15px; background-image: linear-gradient(to top right,#EF6DA0,#EE8E6B);" href="{% url 'calendarapp:calendar' %}?{{ prev_month }}"> << Previous Month </a>
	<a class="btn btn-light m-2 p-2" style="color: white; border-radius:15px; background-image: linear-gradient(to top right,#EF6DA0,#EE8E6B);"  href="{% url 'calendarapp:calendar' %}?{{ next_month }}"> Next Month >> </a>
    {% if request.user.profile.is_cr %}
    <a class="btn border border-light m-2 shadow p-2" style="color: white; border-radius:15px; background-image:linear-gradient(to top right, #8360c3 , #2ebf91); " href="{% url 'calendarapp:event_new' %}"> + New Event </a>
    <a class="btn border border-light shadow p-2" style="color: white; border-radius:15px; background-image: linear-gradient(to top right, #8360c3 , #2ebf91);" href="{% url 'calendarapp:add_news' %}">+ Add News</a>
    {% endif %}
    <!--</div>-->
    <h3 class="d-flex justify-content-center mt-3">Calendar</h3>
    <div class="d-flex justify-content-center shadow p-4">
    {{calendar|safe}}
    </div>
    <div class='shadow p-3 m-3' style='align-content:center;'>
        <h4>Legend</h4>
        <p><button type="button" class="btn btn-danger" style='height:40px;width:40px;'><span style='font-style:bold;font-size:2.5vh;'>5</span></button><i class="fas fa-arrow-right ml-4"></i> Event Date is Crossed</p><br>
        <p><button type="button" class="btn btn-success" style='height:40px;width:40px;'><span style='font-style:bold;font-size:2.5vh;'>10</span></button><i class="fas fa-arrow-right ml-4"></i> Upcoming Event (Click on the date to see the events)</p><br>
        <p><button type="button" class="btn btn-primary" data-toggle="modal" data-target='#day{day}' disabled style='height:40px;width:40px;'><span style='font-style:bold;font-size:2.5vh;'>15</span></button><i class="fas fa-arrow-right ml-4"></i> No Events</p><br>
    </div>
    </div>
{% endblock content %}

calendarapp/templates/calendarapp/event-details.html
{% extends 'user/base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div class="container">
        <div class="clearfix">
          {% if request.user.profile.is_cr %}
            <a class="btn btn-primary float-right mr-2" style="border-radius:5px;" href="{% url 'calendarapp:event_edit' event.pk %}"> Edit Event </a>
          {% endif %}
        </div>
        <div id="reload_status">
        {% if request.user in eventmembers %}
            <p class="btn btn-success shadow-lg" style="border-radius:5px;">
             <i class="fa fa-info-circle"></i> You are a participant in this CRD
             </p>
        {% else %}
            <p class="btn btn-danger shadow-lg" style="border-radius:5px;">
             <i class="fa fa-info-circle"></i> You are not a participant in this CRD
             </p>
        {% endif %}
        {% if request.user not in eventmembers and event.disable_add == False%}
                {% if request.user.profile.cgpa > event.cgpa %}
                <table class="table table-bordered shadow">
                    <thead>
                        <tr>
                          <th style="width: 10px">#</th>
                          <th>Roll No</th>
                          <th>Name</th>
                          <th>Section</th>
                          <th>CGPA</th>
                          <th>Percentage</th>
                          <th>Add</th>
                          <th>Status</th>
                        </tr>
                      </thead>
                      <tbody>
                      <tr role="row">
                            <td>1.</td>
                            <td><a href="{% url 'profile_detail' request.user.username %}">{{ request.user.profile.roll_no }}</a></td>
                            <td>{{ request.user.first_name}}</td>
                            <td>{{ request.user.profile.section}}</td>
                            <td>{{ request.user.profile.cgpa}}</td>
                            <td>{{ request.user.profile.percentage}}</td>
                            <td>
                              {% csrf_token %}
                              {% if request.user in eventmembers %}
                                <p>Applied</p>
                              {% else %}
                                <input type="checkbox" class="add" name="{{user.id}}" id="user{{user.id}}"  user_id='{{user.id}}' event_id='{{event.id}}'>
                                <label for="user{{user.id}}">Participate</label>
                              {% endif %}
                            </td>
                            <td id="load">{% if request.user in eventmembers %}Done!{%else%}Click on participate<br> to start{%endif%}</td>
                        </tr>
                        </tbody>
                    </table>
                    <small>Contact CR for any info.</small><br>
        {% else %}
                    <p class="shadow p-2 m-4">Sorry! You didn't meet Placement criteria! Checkout other placements</p>
        {% endif %}
        {% else %}
                    <p class="shadow p-2 m-4 text-center">Cannot enter the event. Only for selected participants!</p>
        {%endif %}
        </div>
        <div class="row">
        <div class="col-md-8 mr-3 mb-3 pt-3 shadow-lg"  style="border-radius:5px;">
            <h5>Placement Name: {{ event.title }} <p class="badge badge-success">{{event.next_level}}</p></h5>
            <p>From <span>{{ event.start_time }}</span> To <span >{{ event.end_time }}</span></p>
            <hr>
            <p>Description: {{ event.description }}</p>
            <p class="badge badge-secondary">Total Participants {{eventmembers.count}}</p>
            {% if request.user.profile.is_cr %}
            <a href="{% url 'calendarapp:export_presentees_csv' event.id %}" class="btn btn-light m-3 ">Download Participants list</a>
            <a href="{% url 'calendarapp:export_absentees_csv' event.id %}" class="btn btn-light m-3">Download Absentees list</a>
            {% endif %}
        </div>
        <div class="col-md-3 p-3 mb-3 shadow-lg" style="border-radius:5px;">
            <h5 class="text-center">Placement Criteria</h5>
            <hr>
            <p>Inter: {{event.inter}}</p>
            <p>Tenth: {{event.tenth}}</p>
            <p>Graduation: {{event.cgpa}}</p>
        </div>
        </div>
        <hr>
        <div class="clearfix">
            <h4 class="left" > Members of this Event</h4>
        </div>
        <table class="table table-bordered shadow-lg" id="reload_students">
          <thead>
              <tr>
                <th style="width: 10px">#</th>
                <th>Roll No</th>
                <th>Name</th>
                <th>CGPA</th>
                <th>Percentage</th>
              </tr>
            </thead>
            <tbody>
              {% for user in eventmembers %}
              <tr role="row">
                  <td>{{ forloop.counter }}</td>
                  <td><a href="{% url 'profile_detail' user.username%}">{{ user.profile.roll_no }}</a></td>
                  <td>{{ user.first_name }}</td>
                  <td>{{ user.profile.cgpa}}</td>
                  <td>{{ user.profile.percentage}}</td>
              </tr>
              {% endfor %}
            </tbody>
      </table>
      {% if request.user.profile.is_cr %}
        <h4>Sort and Add</h4>
        <small>Presorted {{request.user.profile.section}} section</small>
        <div class="mb-4">
          {% if users.form %}
          <form method='GET' class="m-5 form-inline ">
            {% bootstrap_form users.form %}&nbsp;&nbsp;
            <button class="btn btn-dark shadow">Search</button>
          </form>
          {% endif %}
        </div>
        <table class="table table-bordered shadow-lg">
            <thead>
                <tr>
                  <th style="width: 10px">#</th>
                  <th>Roll No</th>
                  <th>Name</th>
                  <th>CGPA</th>
                  <th>Percentage</th>
                  <th>Add</th>
                </tr>
              </thead>
              <tbody>
                {% for k in users.qs %}
                <tr role="row">
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'profile_detail' k.user.username%}">{{ k.roll_no }}</a></td>
                    <td>{{ k.user.first_name}}</td>
                    <td>{{ k.cgpa}}</td>
                    <td>{{ k.percentage}}</td>
                    <td>
                      {% csrf_token %}
                      {% if k.user in eventmembers %}
                        <input type="checkbox" class="add" name="{{k.id}}" id="user{{k.user.id}}"  user_id='{{k.user.id}}' event_id='{{event.id}}' checked></input>
                      {% else %}
                        <input type="checkbox" class="add" name="{{k.id}}" id="user{{k.user.id}}"  user_id='{{k.user.id}}' event_id='{{event.id}}'></input>
                      {% endif %}
                    </td>
                </tr>
                {% endfor %}
              </tbody>
        </table>
        {% endif %}
<small>This web page reloads data automatically. No need to reload page after confirming your CRD participation.</small>
    </div>
    <div id="notification" class="fixed-bottom col-md-5">
     </div>
{% endblock %}

{% block javascript %}
<script  type="text/javascript">
$('.add').click(function(){
    $.ajax({
          type:'POST',
          url:'/event/add_student_to_event/',
          data:{
            'user_id':$(this).attr('user_id'),
            'event_id':$(this).attr('event_id'),
            'csrfmiddlewaretoken':$('input[name=csrfmiddlewaretoken]').val(),
          },
          beforeSend:function(){
              console.log("hello");
              $('#notification').html(`<div class="alert alert-warning alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                     Adding you to CRD...Please wait...
                     <h4 class="alert-heading">Wait for a second!</h4>
                      <p>Searching for you in vast CR Space!</p>
                      <hr>
                      <p class="mb-0">Found You! Making Changes...hang in there.</p>
                 </div>`);
          },
          complete: function () {
               $("#reload_students").load(" #reload_students");
               $("#reload_status").load(" #reload_status");
            },
          success:function(data){
              $('#load').html('<p>Done!</p>');
              $('#notification').html(`<div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                     <h4 class="alert-heading">Verification</h4>
                      <p>Aww yeah, you successfully completed registration process for this CRD.</p>
                      <hr>
                      <p class="mb-0">Follow CR Space Blog for updates</p>
                  </div>`);
              $("#notification").fadeTo(5000, 500).slideUp(500, function(){
              $("#notification").slideUp(500);
          });
          }});
  });

</script>
{% endblock %}

calendarapp/templates/calendarapp/event.html
{% extends 'user/base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6 shadow-lg d-flex justify-content-center align-items-center p-4 border border-light" style="color: white; border-radius:15px; background-image:linear-gradient(to bottom left, #8360c3 , #2ebf91);">
            <form method="POST" autocapitalize="off" {% if form.is_multipart %} enctype="multipart/form-data"{% endif %} >
                <legend align="center">New Event</legend>
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-light shadow float-right"> Submit </button>
            </form>
        </div>
    </div>
    <br><br>
</div>
{% endblock %}

calendarapp/templates/calendarapp/event_delete.html
<!-- templates/article_delete.html -->
{% extends 'user/base.html' %}

{% block title %}
Event Delete
{% endblock %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete this event?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock content %}

calendarapp/templates/calendarapp/latestnews.html
<div class="pt-3 pl-2 ">
<div class="">
<h5>Latest News</h5>
</div>
<hr>
<div class="p-1" style="height: 200px;overflow-y:scroll;">
{% if latest_news %}
        {%for post in latest_news %}
            <p class="shadow p-2 border border-warning">&#9930; {{post.post_data}}<sup class="badge badge-danger">new</sup><span class='ml-4'>&nbsp;&nbsp;</span><br></p>
        {%endfor%}
{%endif%}
{% if news %}
        {%for post in news %}
           <p class="shadow p-2 border border-warning">&#9930; {{post.post_data}}<br></p>
        {%endfor%}
{%endif%}
{% if not news and not latest_news %}
    There are no news as of now please add anything to show.
{%endif%}
</div>
</div>
<br><br>