blog/urls.py
from django.urls import path,include

from .views import (
    PostUpdateView,
    PostDeleteView,
    TagPostListView,
    UserPostListView,
    post_create,
)
from . import views

urlpatterns = [
    path('', views.home, name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('<post_id>/detail_view/', views.post_detail, name='post-detail'),
    path('post/new/', views.post_create, name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('tag/<str:tagname>',TagPostListView.as_view(),name='tag_posts'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('k/', include('filer.server.urls')),
    path('', include('user.urls')),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('nadmin/',admin.site.urls),
    path('comment/', include('comment.urls')),
    path("a/", include("account.urls")),
    path('tinymce/', include('tinymce.urls')),
    path("b/", include("blog.urls")),
    path("t/", include("teams.urls")),
    path("m/", include("meeting.urls")),
    path("a_r/", include("attendance_request.urls")),
    path("c/", include("contacts.urls")),
    path("e/", include("calendarapp.urls")),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('td/', include('todo.urls', namespace="todo")),
    path('filer/', include('filer.urls')),
    # path('robots.txt',robots),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericRelation
from hitcount.models import HitCount, HitCountMixin
from comment.models import Comment
from taggit.managers import TaggableManager
from tinymce import models as tinymce_models

class Post(models.Model, HitCountMixin):
    title = models.CharField(max_length=100)
    content = tinymce_models.HTMLField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comments = GenericRelation(Comment)
    tags = TaggableManager()
    hit_count_generic = GenericRelation(
    HitCount, object_id_field='object_pk',
    related_query_name='hit_count_generic_relation')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('home')

blog/forms.py
from tinymce.widgets import TinyMCE
from django import forms
from .models import Post
from django.contrib.auth.models import User
from django.forms import Textarea

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=TinyMCE(attrs={'cols':80,'rows':30}))
    class Meta:
        model = Post
        fields = ['title','content','tags']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(PostForm, self).__init__(*args, **kwargs)
    

blog/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.contrib.auth.decorators import login_required
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .filters import PostFilter
from .forms import *
from taggit.models import Tag
from hitcount.models import HitCount
from hitcount.views import HitCountMixin



def home(request):
   #Querying required data
    post_list = Post.objects.all().order_by('-date_posted')
    post_filter = PostFilter(request.GET, queryset=post_list)

    paginator =Paginator(post_filter.qs,10)
    page_request_var="page"
    page=request.GET.get(page_request_var)
    try:
        queryset=paginator.get_page(page)
    except PageNotAnInteger:
        queryset=paginator.get_page(1)
    except EmptyPage:
        queryset=paginator.get_page(paginator.num_pages)

    #Sending data to page
    context={
        "posts":queryset,
        "page_request_var":page_request_var,
        'post_filter':post_filter,
    }
    return render(request, 'blog/home.html', context)


# DEPRECATED LIST VIEW (CURRENT LIST VIEW IS -> HOME VIEW)
# class PostListView(ListView):
#     model = Post
#     template_name = 'blog/home.html'  # <app>/<model>_<viewtype>.html
#     context_object_name = 'posts'
#     ordering = ['-date_posted']
#     paginate_by = 3


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


def post_detail(request, post_id):
    post=Post.objects.get(id=post_id)
    hit_counts=post.hit_count.hits
    hit_count = HitCount.objects.get_for_object(post)
    hit_count_response = HitCountMixin.hit_count(request, hit_count)
    return render(request, 'blog/post_detail.html',{'post':post})

@login_required
def post_create(request):
    if request.method == 'POST':
        post_form = PostForm(request.POST,user=request.user)
        if post_form.is_valid():
            post_form.instance.author = request.user
            post_form.save()
            return redirect('blog-home')
    else:
        post_form = PostForm(user=request.user)
        context = {'form':post_form}
        return render(request,'blog/post_form.html',context=context)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/blog'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class TagPostListView(ListView):
    model = Post
    template_name = "blog/home.html"  # <app>/<model>_<viewtype>.html
    context_object_name = "posts"
    paginate_by = 10

    def get_queryset(self):
        tag = get_object_or_404(Tag, name=self.kwargs.get("tagname"))
        return Post.objects.filter(tags=tag)

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
    <link rel="icon" href="media/default.png">
  {% if title%}
  <title>BooKeeper - {{  title  }}</title>
  {%else%}
  <title>BooKeeper</title>
  {%endif%}
</head>

<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md bg-dark navbar-dark navbar-fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">
          <img src="{%static 'icon.ico'%}" alt="Logo" style="width:40px;">
        </a>
        <a class="navbar-brand mr-4" style="font-size:25px;"href="/">BooKeeper</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{% url 'home' %}">Books</a>
            <a class="nav-item nav-link" href="{% url 'blog-home' %}">Blog</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if request.user.is_authenticated %}
            <div class="btn-group">
              <a class="nav-item nav-link" href="{% url 'profile' %}" style="font-size: 16px;"><img src="{{user.profile.image.url}}" alt="" height="30px" width="30px" class="mr-2 rounded-circle">{{request.user.username}}</a>
          <button type="button" class="btn btn-outline-light dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="sr-only">Toggle Dropdown</span>
          </button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'profile' %}" style="font-size: 16px;">Profile</a>
              <a class="dropdown-item" href="{% url 'favorites' %}">Favourites</a>
              <a class="dropdown-item" href="{% url 'home' %}">Reads</a>
              </div>
        </div>
            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{% url 'about' %}"> About </a>
            <a class="nav-item nav-link" href="{% url 'login' %}"> LogIn </a>
            <a class="nav-item nav-link" href="{% url 'register' %}"> SignUp </a>
            {% endif%}
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-5">
            {% block svg %}
            {% endblock svg %}
      </div>
      <div class="col-md-7">
      {% if messages %}
        {% for message in messages %}
          <div class = "alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
      {% endif %}
        {% block content %}
        {% endblock content %}
      </div>
    </div>
  </main>
  <br><br><br>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
  <!-- Footer -->
  <section id="footer">
      <div class="container">
        <div class="row text-center text-xs-center text-sm-left text-md-left">
          <div class="col-xs-12 col-sm-4 col-md-4">
            <h5>Reader</h5>
            <ul class="list-unstyled quick-links">
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>About</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Books</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Get Started</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Favorites</a></li>
            </ul>
          </div>
          <div class="col-xs-12 col-sm-4 col-md-4">
            <h5>Author</h5>
            <ul class="list-unstyled quick-links">
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Author Search</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Add Author</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>View Author</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Update Author</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>#</a></li>
            </ul>
          </div>
          <div class="col-xs-12 col-sm-4 col-md-4">
            <h5>Book</h5>
            <ul class="list-unstyled quick-links">
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Home</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>About</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>FAQ</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Get Started</a></li>
              <li><a href="https://wwwe.sunlimetech.com" title="Design and developed by"><i class="fa fa-angle-double-right"></i>Imprint</a></li>
            </ul>
          </div>
          <div class="col-xs-12 col-sm-4 col-md-4">
            <h5>BooKeeper System</h5>
            <ul class="list-unstyled quick-links">
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Users Online : {{ request.online_now |length }}</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>About</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>FAQ</a></li>
              <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Get Started</a></li>
              <li><a href="https://wwwe.sunlimetech.com" title="Design and developed by"><i class="fa fa-angle-double-right"></i>Imprint</a></li>
            </ul>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
            <ul class="list-unstyled list-inline social text-center">
              <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-facebook"></i></a></li>
              <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-twitter"></i></a></li>
              <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-instagram"></i></a></li>
              <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-google-plus"></i></a></li>
              <li class="list-inline-item"><a href="javascript:void();" target="_blank"><i class="fa fa-envelope"></i></a></li>
            </ul>
          </div>
          </hr>
        </div>	
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
            <p><u><a href="#">BooKeeper</a></u></p>
            <p class="h6">&copy All right Reversed.<a class="text-green ml-2" href="#" target="_blank">BooKeeper</a></p>
          </div>
          </hr>
        </div>	
      </div>
    </section>
</body>
</html>

blog/templates/blog/home.html
{% extends "user/base.html" %}
{% load bootstrap4 %}
{% load static %}
{% load hitcount_tags %}
{% block content %}
<div class="d-flex justify-content-between container rounded p-2">
  <h4 class="text-dark lead">GIT Blog</h4>
  <abbr title="Create New Post"><a class="btn shadow" href="{% url 'post-create' %}" style="color: white; border-radius:25px; background-image: linear-gradient(to top left, #FE5F75,#FC9842);"><i class="fas fa-plus"></i> &nbsp;New Post</a></abbr>
</div>
<div class="container">
  {% if post_filter.form %}
  <form method='GET' class="form-inline my-2 my-lg-0 justify-content-center pb-5">
    {% bootstrap_form post_filter.form %}&nbsp;&nbsp;
    <button class="btn shadow" style="color: white; border-radius:25px; background-image: linear-gradient(to top left, #8360c3 , #2ebf91);">Search</button>
  </form>
  {% endif %}
    {% for post in posts %}
        {% if forloop.counter|divisibleby:2 %}
        <article class="shadow mb-3 p-2 border border-white"  style="color: white; border-radius:25px; background-image: linear-gradient(to top right,#8360c3 , #2ebf91);">
          <div class="media-body media1 p-2">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-posts' post.author.username %}" style="color:white">{{ post.author.first_name }}</a>
              <small>{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h4 style="height: auto;font-size: larger;"><a href="{% url 'post-detail' post.id %}" style="color:white">{{ post.title }}</a></h4>
            <small><span>{{ post.hit_count.hits }}</span> views</small><br>
              {% for tag in post.tags.all %}
                  <a class="mr-6" href="{% url 'tag_posts' tag %}"><span class="badge badge-light btn-outline-dark">#{{tag}}</span></a>
              {% endfor %}
          </div>
        </article>
        {% else %}
        <article class="shadow mb-3 p-2 border border-white"  style="color: white; border-radius:25px; background-image: linear-gradient(to bottom left,#EF6DA0,#EE8E6B);">
          <div class="media-body media1 p-2">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-posts' post.author.username %}" style="color:white">{{ post.author.first_name }}</a>
              <small>{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h4 style="height: auto;font-size: larger;"><a href="{% url 'post-detail' post.id %}" style="color:white">{{ post.title }}</a></h4>
            <small><span>{{ post.hit_count.hits }}</span> views</small><br>
              {% for tag in post.tags.all %}
                  <a class="mr-6" href="{% url 'tag_posts' tag %}"><span class="badge badge-light btn-outline-dark">#{{tag}}</span></a>
              {% endfor %}
          </div>
        </article>
        {%endif %}
    {% endfor %}
  </div>
<script src="{% static 'hitcount/jquery.postcsrf.js' %}"></script>
<script type="text/javascript">
jQuery(document).ready(function($) {
  // use the template tags in our JavaScript call
  $.postCSRF("{{ hitcount.ajax_url }}", { hitcountPK : "{{ hitcount.pk }}" })
    .done(function(data){
      $('<i />').text(data.hit_counted).attr('id','hit-counted-value').appendTo('#hit-counted');
      $('#hit-response').text(data.hit_message);
  }).fail(function(data){
      console.log('POST failed');
      console.log(data);
  });
});
</script>


    <ul class="pagination justify-content-center">
      {% if posts.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
      <li class="page-item"><a class="page-link" href="?{{ page_request_var }}={{ posts.previous_page_number }}">{{posts.number|add:"-1"}}</a></li>
      {% endif %}
      <li class="page-item active"><p class="page-link">{{ posts.number }} </p></li>
      {% if posts.has_next %}
      <li class="page-item"><a class="page-link" href="?{{ page_request_var }}={{ posts.next_page_number }}"> {{posts.number|add:"1"}}</a></li>
      <li class="page-item"><a class="page-link" href="?{{ page_request_var }}={{ posts.paginator.num_pages }}">Last</a></li>
      {% endif %}
    </ul>
{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends "user/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "user/base.html" %}
{% load comment_tags %}
{% block content %}
{% load humanize %}
  <div class="container">
    <h3 style="font-size:xx-large;font-family:Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;font-weight: 200;">{{ post.title }}</h3>
  <div class="row inline d-flex align-items-center">
    <img src="{{post.author.profile.image.url}}" alt="" class="w-5 h-5" style="width:30px;">

    <div class="col inline">
      <div class="inline follow_div">
        <a href="{% url 'user-posts' post.author.username %}" class="text-muted" style="text-decoration:none;font-size:large;">{{post.author.first_name}}</a>
        {% if post.author != user %}
          {% csrf_token %}
          <button href="" class="btn-sm btn-dark rounded follow ml-2" style="font-size: small;">Follow</button>
        {% endif %}
      </div>
      <div class="inline">
        <small class="text-muted" style="font-size: small;">{{ post.date_posted|date:"F d, Y" }}</small>
        <small class="text-muted" style="font-size: small;">&bull; {{post.hit_count.hits}} Views</small>
      </div>
    </div>
  </div>
  <div class="container-fluid mt-3">
    {% if post.author == request.user %}
          <a class="btn btn-outline-success float-right" href="{% url 'post-update' post.id %}"> Edit Post</a>
          <a class="btn btn-outline-danger float-right mr-2" href="{% url 'post-delete' post.id %}"> Delete Post</a>
    {% endif %}
    <p class="article-content" style="font-size: large;">{{post.content|safe}}</p>
  </div>
  {% for tag in post.tags.all %}
    <a class="mr-1" href="{% url 'tag_posts' tag %}"><span class="badge badge-light btn-outline-dark">#{{tag}}</span></a>
  {% endfor %}
  </div>
  <div class="container rounded shadow-sm">
    {% render_comments post request %}
  </div>
{% endblock content %}
{% block javascript %}
{% endblock %}

blog/templates/blog/post_form.html
{% extends "user/base.html" %}
{% load bootstrap4 %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form.media }}
                {% bootstrap_form form %}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

{% block javascript %}
<script type="text/javascript">
    tinymce.init({
    selector: 'textarea#id_content',
    plugins: 'print preview paste importcss searchreplace autolink autosave save directionality code visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists wordcount imagetools textpattern noneditable help charmap quickbars emoticons',
    imagetools_cors_hosts: ['picsum.photos'],
    menubar: 'file edit view insert format tools table help',
    toolbar: 'undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist | forecolor backcolor removeformat | pagebreak | charmap emoticons | fullscreen  preview save print | insertfile image media template link anchor codesample | ltr rtl',
    toolbar_sticky: true,
    autosave_ask_before_unload: true,
    autosave_interval: "30s",
    autosave_prefix: "{path}{query}-{id}-",
    autosave_restore_when_empty: false,
    autosave_retention: "2m",
    image_advtab: true,
    content_css: '//www.tiny.cloud/css/codepen.min.css',
    link_list: [
        { title: 'My page 1', value: 'http://www.tinymce.com' },
        { title: 'My page 2', value: 'http://www.moxiecode.com' }
    ],
    image_list: [
        { title: 'My page 1', value: 'http://www.tinymce.com' },
        { title: 'My page 2', value: 'http://www.moxiecode.com' }
    ],
    image_class_list: [
        { title: 'None', value: '' },
        { title: 'Some class', value: 'class-name' }
    ],
    importcss_append: true,
    file_picker_callback: function (callback, value, meta) {
        /* Provide file and text for the link dialog */
        if (meta.filetype === 'file') {
        callback('https://www.google.com/logos/google.jpg', { text: 'My text' });
        }

        /* Provide image and alt text for the image dialog */
        if (meta.filetype === 'image') {
        callback('https://www.google.com/logos/google.jpg', { alt: 'My alt text' });
        }

        /* Provide alternative source and posted for the media dialog */
        if (meta.filetype === 'media') {
        callback('movie.mp4', { source2: 'alt.ogg', poster: 'https://www.google.com/logos/google.jpg' });
        }
    },
    templates: [
            { title: 'New Table', description: 'creates a new table', content: '<div class="mceTmpl"><table width="98%%"  border="0" cellspacing="0" cellpadding="0"><tr><th scope="col"> </th><th scope="col"> </th></tr><tr><td> </td><td> </td></tr></table></div>' },
        { title: 'Starting my story', description: 'A cure for writers block', content: 'Once upon a time...' },
        { title: 'New list with dates', description: 'New List with dates', content: '<div class="mceTmpl"><span class="cdate">cdate</span><br /><span class="mdate">mdate</span><h2>My List</h2><ul><li></li><li></li></ul></div>' }
    ],
    template_cdate_format: '[Date Created (CDATE): %m/%d/%Y : %H:%M:%S]',
    template_mdate_format: '[Date Modified (MDATE): %m/%d/%Y : %H:%M:%S]',
    height: 600,
    image_caption: true,
    quickbars_selection_toolbar: 'bold italic | quicklink h2 h3 blockquote quickimage quicktable',
    noneditable_noneditable_class: "mceNonEditable",
    toolbar_mode: 'sliding',
    contextmenu: "link image imagetools table",
    });
</script>
{% endblock %}